services:
  flutter-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: web
    image: flutbook-player:dev
    container_name: flutbook-dev
    platform: linux/amd64
    stdin_open: true
    tty: true

    # IMPORTANT: run as your real user, not root
    user: "1000:1000"   # <--- REPLACE 1000 with your UID if different

    working_dir: /workspace/app

    volumes:
      - ./app:/workspace/app
      - ./.volumes/pub-cache:/home/dev/.pub-cache
      - ./.volumes/flutter-bin:/opt/flutter
      - ./.volumes/android-sdk:/opt/android-sdk-linux

      # X11 Display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Forward host DBus session
      - /run/user/1000/bus:/run/user/1000/bus

      # Required runtime dirs
      - /run/user/1000:/run/user/1000

      # Required so FilePicker can access real paths
      - /home:/home:rw

    ports:
      - "3000:3000"
      - "8000:8000"
      - "8080:8080"
      - "9090:9090"

    environment:
      - FLUTTER_ROOT=/opt/flutter
      - ANDROID_HOME=/opt/android-sdk-linux
      - ANDROID_SDK_ROOT=/opt/android-sdk-linux
      - PUB_CACHE=/home/dev/.pub-cache

      - DISPLAY=${DISPLAY}
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
      - XDG_RUNTIME_DIR=/run/user/1000

      - GDK_BACKEND=x11

    entrypoint: ["/bin/bash"]
