include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    avoid_print: ignore
    avoid_slow_async_io: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - lib/l10n/gen/*
    - assets/my_app/**/*
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
