// This is a placeholder file for Firebase options.
// It's generated by running `flutterfire configure` command.
// For development purposes, this file is created with minimal structure to avoid compilation errors.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // In a real implementation, this would return platform-specific config
    // For now, we return a basic config that will allow compilation
    return const FirebaseOptions(
      apiKey: 'AIza-placeholder-for-development',
      appId: '1:placeholder:web:placeholder',
      messagingSenderId: '123456789',
      projectId: 'placeholder-project-id',
      authDomain: 'placeholder.firebaseapp.com',
      databaseURL: 'https://placeholder.firebaseio.com',
      storageBucket: 'placeholder.appspot.com',
    );
  }
}